apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::988007256003:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1S4WIFF6K3Q5I
      username: system:node:{{EC2PrivateDNSName}}
      - groups:
        - system:masters
        rolearn: arn:aws:iam::988007256003:role/UdacityFlaskDeployCBKubectlRole
        username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-05-23T10:37:41Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "11091"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 6e111e58-9ce1-11ea-83f7-02fba9cad782
